### ISSUE TITLE
按同步後都沒有回應 請問要如何使用

### ISSUE THREAD

**Issue by james203198191** [andrew0928/WebServerClock#2]
你好 我今天輸入 http://railway.hinet.net 按同步後都沒有回應 請問要如何使用
時間差: +00000 msec, 最大誤差值: +00000 msec

**Comment by andrew0928** [comment]
看了一下， http://railway.hinet.net 這個網址已經無效了, 沒偵測到回應就不會去修正時間差跟誤差統計。

現在台鐵訂票網站網址改為:
https://www.railway.gov.tw/

測試過後就可以正常運作了
![image](https://user-images.githubusercontent.com/15281111/234470197-37c599b7-5c93-4b9b-b0ad-a6358168fe32.png)

**Comment by james203198191** [comment]
可以了 謝謝 
台鐵訂票網站網址
https://www.railway.gov.tw/
